server:
  port: 8089

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.web.reactive: TRACE
    org.springframework.boot.autoconfigure.web: TRACE
    reactor.netty: TRACE
    io.netty: TRACE
    io.grpc: TRACE